import type { Metadata } from "next";
import { Inter, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "../lib/apolloProvider" 
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Navbar from "./components/Navbar";
import ThemeProvider from "./components/ThemeProvider";
// Load fonts
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });

// Page metadata
export const metadata: Metadata = {
  title: "CRUD APP",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
        <ApolloWrapper>
          <ThemeProvider>
          {children}
          </ThemeProvider>
        </ApolloWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
